config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/maps'
  get 'pages/marker_maps'
  root "destinations#index"
  resources :destinations

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :image, :title, :post)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def maps
  end
  
  def marker_maps
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/destinations/_form.html.erb
<%= form_for @destination, html: { multipart: true } do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :post %><br>
    <%= f.text_area :post, rows: "10", class:'form-control' %>
  </div>
  <div class="actions">
    <div class="actions row text-center">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="row text-center">Destinations</h1>
</br>
<% if @destinations.any? %>
  <% @destinations.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.compact.each do |destination| %>
        <div class="col-xs-4" style="margin-top: 20px;">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= link_to image_tag(destination.image_url, :width => '100%', :height => '200px'), destination if destination.image.present?%>
            </div>
            <div class="panel-footer">
              <h4 class="text-center"><%= link_to destination.name, destination %></h4>
              <p class="text-center"><%= destination.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else  %>
   <p>No destinations found.</p>
<% end %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin:auto; width: 60%">
<h1 class=" text-center" style="margin-bottom: 30px;" >
  <strong><%= @destination.name %></strong>
</h1>

<p class="text-center">
  <%= image_tag(@destination.image_url, :width => 600) if @destination.image.present? %>
</p>

<h2 class="text-center">
  <strong><%= @destination.title %></strong>
</h2>

<p style="white-space: pre-line;">
  <%= @destination.post %>
</p>

<br/>

<p class="text-center">
  <%= link_to 'Edit', edit_destination_path(@destination) %> |
  <%= link_to 'Delete', @destination, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to 'Back', destinations_path %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rgtravelguide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://js.cit.api.here.com/v3/3.0/mapsjs-ui.css" />
  <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-core.js"></script>
  <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-service.js"></script>
  <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-ui.js"></script>
  <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-mapevents.js"></script>
</head>
<body>
  
 <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RGTravelGuide", destinations_path, class: "navbar-brand" %>
    </div>
    <p class="navbar-text navbar-right">
  <%= link_to 'About', pages_about_path, class:'navbar-link' %>
</p>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Destinations", destinations_path %></li>
        <li><%= link_to 'Add New Destination', new_destination_path %></li>
        <li><%= link_to 'Maps', pages_maps_path %></li>
        <li><%= link_to 'Marker_Maps', pages_marker_maps_path %></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container">
  <%= yield %>
</div>
  
 <footer class="footer">
  <div class="container">
    <p class="text-muted">Rails Girls KL 2018</p>
  </div>
</footer>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<h1>Blahblahblah</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/maps.html.erb
 <div id="map" style="position:absolute; width:100%; height:100%; background:grey" ></div>
<script  type="text/javascript" charset="UTF-8" >
  function setUpClickListener(map) {
map.addEventListener('tap', function (evt) {
var coord = map.screenToGeo(evt.currentPointer.viewportX,
 	evt.currentPointer.viewportY);
alert('Clicked at ' + Math.abs(coord.lat.toFixed(6)) +
 				((coord.lat > 0) ? 'N' : 'S') +
' ' + Math.abs(coord.lng.toFixed(6)) +
 ((coord.lng > 0) ? 'E' : 'W'));
 });
}
  var platform = new H.service.Platform({
app_id: 'Ktp5ly1lipgQ42mtaPg4',
app_code: 'HWDJHPJUmiXwEAJ4X0SmcA',
useCIT: true,
useHTTPS: true
});
var defaultLayers = platform.createDefaultLayers();
  var map = new H.Map(document.getElementById('map'),
defaultLayers.normal.map,{
center: {lat: 8.800, lng: 111.8471577 },
zoom: 5
});
var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));
setUpClickListener(map);
</script> 

app/views/pages/marker_maps.html.erb
<h1>Search for a Location based on an Address #Mylocationforcommunity</h1>
    
    <div id="map" style="width: 600px; height: 400px; background: grey"></div>
    <div id="panel" style="width: 600px;"></div>
    <script type="text/javascript">
      
function geocode(platform) {
  var geocoder = platform.getGeocodingService(),
    geocodingParameters = {
      searchText: 'Place Charles de Gaulle, 75008 Paris, France',      
      jsonattributes : 1
    };
  geocoder.geocode(
    geocodingParameters,
    onSuccess,
    onError
  );
}
/**
 * This function will be called once the Geocoder REST API provides a response
 * @param  {Object} result          A JSONP object representing the  location(s) found.
 *
 * see: http://developer.here.com/rest-apis/documentation/geocoder/topics/resource-type-response-geocode.html
 */
function onSuccess(result) {
  var locations = result.response.view[0].result;
 /*
  * The styling of the geocoding response on the map is entirely under the developer's control.
  * A representitive styling can be found the full JS + HTML code of this example
  * in the functions below:
  */
  addLocationsToMap(locations);
  addLocationsToPanel(locations);
  // ... etc.
}
/**
 * This function will be called if a communication error occurs during the JSON-P request
 * @param  {Object} error  The error message received.
 */
function onError(error) {
  alert('Ooops!');
}
/**
 * Boilerplate map initialization code starts below:
 */
//Step 1: initialize communication with the platform
var platform = new H.service.Platform({
  app_id: 'Ktp5ly1lipgQ42mtaPg4',
  app_code: 'HWDJHPJUmiXwEAJ4X0SmcA',
  useCIT: true,
  useHTTPS: true
});
var defaultLayers = platform.createDefaultLayers();
//Step 2: initialize a map - this map is centered over California
var map = new H.Map(document.getElementById('map'),
  defaultLayers.normal.map,{
  center: {lat:37.376, lng:-122.034},
  zoom: 15
});
var locationsContainer = document.getElementById('panel');
//Step 3: make the map interactive
// MapEvents enables the event system
// Behavior implements default interactions for pan/zoom (also on mobile touch environments)
var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));
// Create the default UI components
var ui = H.ui.UI.createDefault(map, defaultLayers);
// Hold a reference to any infobubble opened
var bubble;
/**
 * Opens/Closes a infobubble
 * @param  {H.geo.Point} position     The location on the map.
 * @param  {String} text              The contents of the infobubble.
 */
function openBubble(position, text){
 if(!bubble){
    bubble =  new H.ui.InfoBubble(
      position,
      {content: text});
    ui.addBubble(bubble);
  } else {
    bubble.setPosition(position);
    bubble.setContent(text);
    bubble.open();
  }
}
/**
 * Creates a series of list items for each location found, and adds it to the panel.
 * @param {Object[]} locations An array of locations as received from the
 *                             H.service.GeocodingService
 */
function addLocationsToPanel(locations){
  var nodeOL = document.createElement('ul'),
    i;
  nodeOL.style.fontSize = 'small';
  nodeOL.style.marginLeft ='5%';
  nodeOL.style.marginRight ='5%';
   for (i = 0;  i < locations.length; i += 1) {
     var li = document.createElement('li'),
        divLabel = document.createElement('div'),
        address = locations[i].location.address,
        content =  '<strong style="font-size: large;">' + address.label  + '</strong></br>';
        position = {
          lat: locations[i].location.displayPosition.latitude,
          lng: locations[i].location.displayPosition.longitude
        };
      content += '<strong>houseNumber:</strong> ' + address.houseNumber + '<br/>';
      content += '<strong>street:</strong> '  + address.street + '<br/>';
      content += '<strong>district:</strong> '  + address.district + '<br/>';
      content += '<strong>city:</strong> ' + address.city + '<br/>';
      content += '<strong>postalCode:</strong> ' + address.postalCode + '<br/>';
      content += '<strong>county:</strong> ' + address.county + '<br/>';
      content += '<strong>country:</strong> ' + address.country + '<br/>';
      content += '<br/><strong>position:</strong> ' +
        Math.abs(position.lat.toFixed(4)) + ((position.lat > 0) ? 'N' : 'S') +
        ' ' + Math.abs(position.lng.toFixed(4)) + ((position.lng > 0) ? 'E' : 'W');
      divLabel.innerHTML = content;
      li.appendChild(divLabel);
      nodeOL.appendChild(li);
  }
  locationsContainer.appendChild(nodeOL);
}
/**
 * Creates a series of H.map.Markers for each location found, and adds it to the map.
 * @param {Object[]} locations An array of locations as received from the
 *                             H.service.GeocodingService
 */
function addLocationsToMap(locations){
  var group = new  H.map.Group(),
    position,
    i;
  // Add a marker for each location found
  for (i = 0;  i < locations.length; i += 1) {
    position = {
      lat: locations[i].location.displayPosition.latitude,
      lng: locations[i].location.displayPosition.longitude
    };
    marker = new H.map.Marker(position);
    marker.label = locations[i].location.address.label;
    group.addObject(marker);
  }
  group.addEventListener('tap', function (evt) {
    map.setCenter(evt.target.getPosition());
    openBubble(
       evt.target.getPosition(), evt.target.label);
  }, false);
  // Add the locations group to the map
  map.addObject(group);
  map.setCenter(group.getBounds().getCenter());
}
// Now use the map as required...
geocode(platform);
    </script>